name: 将博客自动部署到七牛云

on:
  push:
    branches: [ master ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: 安装 Ruby 2.6
        uses: actions/setup-ruby@v1
        with:
          ruby-version: 2.6
      - name: 将 master 分支检出
        uses: actions/checkout@v2
      - uses: actions/cache@v2
        with:
          path: vendor/bundle
          key: ${{ runner.os }}-gems-${{ hashFiles('**/Gemfile.lock') }}
      - name: 使用 bundle 安装 github-pages
        run: |
          bundle init && \
          bundle config path vendor/bundle && \
          bundle add github-pages
      - name: 构建静态文件
        run: bundle exec jekyll build
      - name: 下载 qshell 工具
        run: |
          wget http://devtools.qiniu.com/qshell-linux-x64-v2.4.2.zip -O qshell.zip && \
          unzip qshell.zip -d tmp && \
          mv tmp/qsh* qshell
      - name: 查看目录文件
        run: ls
      - name: 给 qshell 权限
        run: chmod +x qshell
      - name: 将 404 文件修改
        run: mv ./_site/errno-404.html ./_site/errno-404
      - name: 使用 qshell 执行上传命令
        run: |
          ./qshell account ${{ secrets.QINIU_AK }} ${{ secrets.QINIU_SK }} blogfile && \
          ./qshell qupload2 --src-dir=./_site --bucket=zy-blogfile --check-exists --check-hash --thread-count=5 --overwrite --success-list=success.txt && \
          echo '===============================================' && \
          echo '=                success.txt                  =' && \
          echo '===============================================' && \
          cat success.txt && \
          echo '===============================================' && \
          cat success.txt | awk '{printf "https://blog.ziying.site/%s\nhttps://www.blog.ziying.site/%s\n", $2, $2}' > refresh.txt && \
          echo '===============================================' && \
          echo '=                refresh.txt                  =' && \
          echo '===============================================' && \
          cat refresh.txt && \
          echo '===============================================' && \
          ./qshell cdnrefresh -i refresh.txt

